---

# These variables are the stock configurations that either alias variables
# from the vault or provide paths that the project itself uses.
# vault variables first
secret_key: '{{ vault_secret_key }}'
mapbox_token: '{{ vault_mapbox_token }}'
db_name: '{{ vault_db_name }}'
db_username: '{{ vault_db_username }}'
db_password: '{{ vault_db_password }}'
db_host: '{{ vault_db_host }}'
email_host_password: '{{ vault_email_host_password }}'
geonames_username: '{{ vault_geonames_username}}'

# project names, version variables, and directories
# Name of the group to run this role on for use in templating section
# should match the host group
group_name: winthrop_prod
# install root for repository checkout
install_root: /srv/www/prod
# Git refspec to use, either default or passed by '-e ref=<refspec>
gitref: '{{ ref | default("master") }}'
# Symlink for /var/www that Apache expects (often different QA and prod)
symlink: 'winthrop'
