---
# Git refspec to use, either default or passed by '-e ref=<refspec>
gitref: '{{ ref | default("develop") }}'
# email prefix for admin emails
email_prefix: "[QA CDH Web] "
# allowed_hosts for Django
allowed_hosts:
    - "test-web.cdh.princeton.edu"
    - "cdh-test-web.princeton.edu"
    - "cdh-test-web1"
    - "localhost"
    - "127.0.0.1"

application_url: "test-web.cdh.princeton.edu"

# passenger settings
passenger_server_name: "{{ application_url }}"
