---
galaxy_info:
  role_name: build_project_repo
  company: Princeton University Library
  description: builds a project repo
  author: pulibrary

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies: []
  # uncomment the line below and remove the `[]` above in your role
  # - role: "<role I depend on>"
