---
- name: Converge
  hosts: all
  vars:
    - running_on_server: false
  become: true
  tasks:
    - name: "Include opencv_from_source"
      ansible.builtin.include_role:
        name: opencv_from_source
