---
galaxy_info:
  role_name: supervisor
  company: Princeton University Library
  description: Refactored Supervisor Role
  author: pulibrary

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies: []
  # uncomment the line below and remove the `[]` above in your role
  # - role: "<role I depend on>"
