###
# Variables for PPA that apply across all deploy groups (prod, qa, and staging)
###
---
# Using python35 and nodejs10 for QA and staging
# Paths are picky and spaces for any YAML multiline syntax causes issues
path: '/opt/rh/rh-python35/root/usr/bin:/opt/rh/rh-nodejs10/root/usr/bin:/opt/rh/rh-git227/root/bin:{{ ansible_env.PATH }}'
ld_library_path: '/opt/rh/rh-python35/root/usr/lib64:/opt/rh/rh-nodejs10/root/usr/lib64{% if ansible_env.LD_LIBRARY_PATH is defined %}:{{ ansible_env.LD_LIBRARY_PATH }}{% endif %}'
python_path: '/opt/rh/rh-nodejs10/root/usr/lib/python2.7/site-packages{% if ansible_env.PYTHON_PATH is defined %}:{{ ansible_env.PYTHONPATH }}{% endif %}'
# Github repository
repo: 'Princeton-CDH/ppa-django'
app_name: ppa
# name of django application
django_app: ppa
# apache symlink
symlink: 'prosody'
# Solr settings for QA and staging (production will override)
solr_collection: ppa
solr_configset: ppa
# path to hathitree pairtree data
hathitrust_pairtree_path: '/home/deploy/ppa/ht_text_pd/'
technical_contact: cdhdevteam@princeton.edu
# flag that csp is enabled
csp_enabled: true
# set a default media root for prod and staging
media_root: '/srv/www/prod/media'
# use python 3.6 (may not matter for virtualenv creation on RedHat)
python_version: "python3.6"
# explicitly specify deploy user
deploy_user: "deploy"
# explicitly set apache user for Springdale
apache_user: "apache"
