---

# These variables are the stock configurations that either alias variables
# from the vault or provide paths that the project itself uses.
# vault variables first
# Secret key for Django application
secret_key: '{{ vault_secret_key }}'
# Secret key for Mapbox API
mapbox_token: '{{ vault_mapbox_token }}'
# Geoname username
geonames_username: '{{ vault_geonames_username }}'
# Plum and figgy tokens
plum_token: '{{ vault_plum_token }}'
figgy_token: '{{ vault_figgy_token }}'
# Database configurations
db_name: '{{ vault_db_name }}'
db_username: '{{ vault_db_username }}'
db_password: '{{ vault_db_password }}'
db_host: '{{ vault_db_host }}'
# Solr configuration
solr_url: '{{ vault_solr_url }}'
solr_admin_url: '{{ vault_solr_admin_url }}'

# project names, version variables, and directories
# Name of the group to run this role on for use in templating section
group_name: derrida_prod
# install root for repository checkout
install_root: /srv/www/prod
# Git refspec to use, either default or passed by '-e ref=<refspec>
gitref: '{{ ref | default("master") }}'
# Symlink for /var/www that Apache expects (often different QA and prod)
symlink: 'derridas-margins'
