---
# defaults for build_dependencies
common_dependencies:
  - acl
  - build-essential
  - curl
  - git
  - unzip
  - zip
  - python-pip
  - python-setuptools
  - libssl-dev
  - wget
  - tmux
  - python-virtualenv
  - snapd
# app-specific dependencies: override to install
app_dependencies: []
