- hosts: pemm_qa
  connection: ssh
  remote_user: pulsys
  become: true
  roles:
    - create_deployment
    - cdh.common
    - install_app_config
    - build_project_repo
    - build_virtualenv
    - configure_logging
    - configure_apache
    - configure_crontab
    - pemm_setup
    - finalize_deploy
    - close_deployment
